CREATE TABLE DEPARTMENTS ( 
    DEPARTMENTS_DEPT_ID INT AUTO_INCREMENT PRIMARY KEY, 
    DEPARTMENTS_NAME VARCHAR(100) NOT NULL 
);

CREATE TABLE STUDENTS ( 
    STUDENT_ID INT PRIMARY KEY, 
    STUDENTS_FIRST_NAME VARCHAR(100) NOT NULL, 
    STUDENTS_LAST_NAME VARCHAR(100) NOT NULL, 
    STUDENTS_EMAIL VARCHAR(150) UNIQUE NOT NULL, 
    STUDENTS_DEPT_ID INT NOT NULL, 
    STUDENTS_JOINING_DATE DATE, 
    FOREIGN KEY (STUDENTS_DEPT_ID) REFERENCES DEPARTMENTS(DEPARTMENTS_DEPT_ID) 
);

CREATE TABLE SUBJECTS ( 
    SUBJECT_ID INT AUTO_INCREMENT PRIMARY KEY, 
    SUBJECT_NAME VARCHAR(150) NOT NULL, 
    SUBJECT_DEPT_ID INT NOT NULL, 
    FOREIGN KEY (SUBJECT_DEPT_ID) REFERENCES DEPARTMENTS(DEPARTMENTS_DEPT_ID) 
);

CREATE TABLE MARKS ( 
    MARKS_STUDENT_ID INT NOT NULL, 
    MARKS_SUBJECT_ID INT NOT NULL, 
    MARKS_SCORED INT CHECK (MARKS_SCORED BETWEEN 0 AND 100), 
    PRIMARY KEY (MARKS_STUDENT_ID, MARKS_SUBJECT_ID), 
    FOREIGN KEY (MARKS_STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID), 
    FOREIGN KEY (MARKS_SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID) 
);

CREATE TABLE GRADES ( 
    GRADES_ID INT PRIMARY KEY, 
    GRADES_CODE VARCHAR(10) NOT NULL, 
    GRADES_LABEL VARCHAR(50) NOT NULL, 
    GRADES_PERCENTAGE_RANGE VARCHAR(20) NOT NULL, 
    GRADES_GPA_EQUIVALENT DECIMAL(2,1) NOT NULL 
);
